spring.application.name=spring-security-jwt
server.port=8080
#spring.security.user.name=user
#spring.security.user.password=password

#db config
spring.datasource.url=jdbc:postgresql://localhost:5432/planonboarding
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

#jpa config
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
#
##swagger properties
#springdoc.api-docs.enabled=true
#springdoc.swagger-ui.enabled=true
#
#springdoc.packages-to-scan=*
##springdoc.paths-to-match=/auth/**
##springdoc.swagger-ui.path=/swagger-ui
##springdoc.api-docs.path=/v3/api-docs
#springdoc.enable-spring-security=false
#springdoc.enable-data-rest=true
#springdoc.swagger-ui.use-root-path=true
#
##springdoc.packagesToScan=com.fis.deloitte.planOnboarding.controller
